@version: 4.3

# Pull from Snort alert volume (configured in readonly in compose.yaml)
source s_snort_alerts {
    file("/var/log/snort/alert_json.txt", follow-freq(1), flags(no-parse));
};

# Push to local file mounted at ./logs
destination d_logs {
    file("/var/log/")
}

log {
    source(s_snort_alerts);
    destination(d_logs);
}